# Page settings

baseURL = ""
relativeURLs = "true"
uglyURLs = "true"
languageCode = "en-us"
title = "Bradley Frank"
theme = "hugo-devresume-theme"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#42A8C0"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Bradley Frank"
        tagline = "Senior SysAdmin & Cloud Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Greater Boston"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:bradfrank@fastmail.com"
        text = "bradfrank@fastmail.com"
        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/bradleymfrank"
        text = "bradleymfrank"
        [[params.contact.list]]
        icon = "fa fa-code"
        url = "https://github.com/bradleyfrank"
        text = "github"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "RHEL/CentOS; Ubuntu"
        [[params.skills.list.items]]
        details = "Docker/Jenkins/Kubernetes"
        [[params.skills.list.items]]
        details = "Ansible/Puppet/Salt"
        [[params.skills.list.items]]
        details = "Bash/Python"
        [[params.skills.list.items]]
        details = "Git; GitHub/GitLab"
        [[params.skills.list.items]]
        details = "MariaDB/MySQL"
        [[params.skills.list.items]]
        details = "VMware vSphere/Cloud"
        [[params.skills.list.items]]
        details = "AWS EC2/VPC/RDS"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Writing Documentation"
        [[params.skills.list.items]]
        details = "Mentoring/Teaching"
        [[params.skills.list.items]]
        details = "Remote Work/Self-Management"
        [[params.skills.list.items]]
        details = "Written/Verbal Communication"
        [[params.skills.list.items]]
        details = "Work/Life Balance"







    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "AWS Certified SysOps Administrator"
        body = ""
        url = "https://www.youracclaim.com/badges/e8be4699-1d77-4e9e-b2ce-436a2b3d69c4"
        date = "July 2020"







    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"







    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Management Information Systems, MA"
        university = "Stevens Institute of Technology"
        dates = "May 2007"
        [[params.education.list]]
        degree = "Computer Science, BA"
        university = "SUNY Geneseo"
        dates = "May 2005"







    [params.summary]
        enable = true
        text = "Systems Administrator and Cloud Engineer with a wide-range of experience with physical, virtual, and container architectures -- from concept to deployment to administration. CS/MIS by education, practical IT by trade. Has a proven track record managing and working with numerous languages, tools, platforms, and people. Experience in non-profits, private industry, and higher education; working on-prem, in the cloud, and with hybrid infrastructures. Can lead teams and mentor juniors. Loves tinkering and developing new skills in his time off."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Systems Administrator"
        dates = "April 2018 — Present"
        company = "Tufts University"
        details = "Managed operations of a hybrid cloud data center running critical university services such as Oracle and MySQL databases, CMS platforms, HR/finance applications, network appliances, and numerous internal toolsets, leveraging our private GitLab infrastructure, Puppet and Salt for configuration management, and Docker and Kubernetes for deploying applications."
        [[params.experience.list.items]]
        details = "Provided on-call escalation: responsible for delegation of client support cases, issue resolution, incident postmortem, and knowledge transfer"
        [[params.experience.list.items]]
        details = "Developed CI/CD pipelines including Docker images, Jenkinsfiles, and deploying Kubernetes resources, to reduce infrastructure overhead"
        [[params.experience.list.items]]
        details = "Coordinated regularly scheduled infrastructure-wide security patching and upgrading of 500+ VMs and appliances"
        [[params.experience.list.items]]
        details = "Managed a full stack Drupal and WordPress hosting environment for university schools, departments, and teams"


        [[params.experience.list]]
        title = "Cloud Engineer"
        dates = "June 2018 — Present"
        company = "Data Privacy Lab"
        details = "Managed AWS infrastructure and associated components (VPC, RDS, CodeCommit, DNS, etc.), supporting securely publishing data from collaborative work with government agencies, and investigative work into privacy within the realm of big data."
        [[params.experience.list.items]]
        details = "Migrated websites from legacy RHEL6 VMs to Ubuntu 18.04 ec2 instances"
        [[params.experience.list.items]]
        details = "Redesigned VPC topology to increase security"
        [[params.experience.list.items]]
        details = "Instituted policies for securing root and user accounts with MFA"
        [[params.experience.list.items]]
        details = "Developed processes for securely deploying code from CodeCommit"
        [[params.experience.list.items]]
        details = "Imported data and deployed RDS instances with read-replicas"

        [[params.experience.list]]
        title = "Systems Administrator"
        dates = "March 2013 — April 2018"
        company = "Harvard-MIT Data Center"
        details = "Worked on a devops team to configure, deploy, and manage 200+ physical, virtual, and cloud-based CentOS servers making up a social science research cluster with adjacent services (DNS, LDAP, web hosting, database hosting, big data storage) that served faculty and students across Harvard."
        [[params.experience.list.items]]
        details = "On-call responsibilities for 24x7 steady-state operations included monitoring for incident response, weekly tape backup rotation, providing tier II and III support for clients, and patching/upgrading servers and appliances"
        [[params.experience.list.items]]
        details = "Deployed Puppet for infrastructure management using Capistrano"
        [[params.experience.list.items]]
        details = "Modernized legacy LAMP hosting platform with Nginx and MariaDB (including multi-master replication and backup)"
        [[params.experience.list.items]]
        details = "Administered NetApp FAS series storage running ONTAP 8 for hosting big data and VM storage"
        [[params.experience.list.items]]
        details = "Mentored junior Systems Administrator in architecture, troubleshooting methodologies, and best practices"
        [[params.experience.list.items]]
        details = "Responsible for managing confidential data (level 5 as per Harvard IRB) across multiple environments and ensuring proper security protocols"

        [[params.experience.list]]
        title = "Systems Project Manager"
        dates = "August 2012 — May 2018"
        company = "Harvard EdLabs"
        details = "Contracted to develop and engineer a secure systems infrastructure — that complied with Harvard’s highest level security requirements — for a team of statistical researchers at the Education Innovation Laboratory, to store and process private, public, and governmental datasets."
        [[params.experience.list.items]]
        details = "Researched and deployed high-performance, multi-user, CentOS 7-based workstations for analyzing big data"
        [[params.experience.list.items]]
        details = "Wrote custom scripts for user management, log retention, data backup, and data onboarding"
        [[params.experience.list.items]]
        details = "Configured systems to meet strict security requirements with intrusion detection, access control policies, removal of network/remote capabilities, data encryption, session locking and expiration, and root logging"
        [[params.experience.list.items]]
        details = "Wrote administrator and user manuals, documented technical setup of workstations, and security compliance checklists for Harvard University and third party data providers"

        [[params.experience.list]]
        title = "IT Support Specialist"
        dates = "July 2011 — March 2013"
        company = "Harvard-MIT Data Center"
        details = "As a member of a small client services team, provided security training and deployment, along with tier I and tier II support for a wide array of hardware, software, mobile devices, and an on-prem High Performance Cluster for hundreds of faculty, staff, and students across several departments."
         [[params.experience.list.items]]
        details = "Built PC imaging process using Acronis True Image, reducing deployment time by dozens of hours"
        [[params.experience.list.items]]
        details = "Quoted and purchased computer equipment, accessories, software, and licenses for departments"
        [[params.experience.list.items]]
        details = "Supported students and faculty using the research cluster virtual desktop environment"

        [[params.experience.list]]
        title = "LAN Administrator"
        dates = "Sept 2010 – July 2011"
        company = "Personal Computers, Inc."
        details = "As part of a MSP, performed dual roles as tier II and tier III remote and on-site support for multiple clients, and a systems administrator overseeing servers, SANs, phone appliances, and networking equipment in a colocation facility."
        [[params.experience.list.items]]
        details = "Supported Domino Admin 6.5 with Lotus Notes, Exchange Server 2003, Zimbra Server 5, and iMail"
        [[params.experience.list.items]]
        details = "Performed tape backups and restores with CA ARCserve and NetApp appliance"
        [[params.experience.list.items]]
        details = "Responsible for a 400+ server data center and steady state operations during 24x7 on-call rotations"
        [[params.experience.list.items]]
        details = "Executed monthly WSUS for Windows 2003 and 2008 servers during overnight maintenance windows"
        [[params.experience.list.items]]
        details = "Developed monitoring applications for critical web hosting processes"

        [[params.experience.list]]
        title = "Systems Administrator I"
        dates = "Oct 2007 – Sept 2010"
        company = "Crystal Run Village, Inc."
        details = "Member of a small team providing comprehensive IT support for a non-profit serving intellectually disabled individuals, and its 50+ residential offices, along with managing mission critical infrastructure and services from the on-site data center."
        [[params.experience.list.items]]
        details = "Performed tape backups and restores with Symantec Backup Exec 2010"
        [[params.experience.list.items]]
        details = "Developed and deployed Windows XP/7 images using Acronis True Image to standardize company-wide PCs"
        [[params.experience.list.items]]
        details = "Installed printers, video conferencing, and networking equipment"
        [[params.experience.list.items]]
        details = "Configured internet proxy and custom web filters"
        [[params.experience.list.items]]
        details = "Performed ethernet punch-down and cable drops for office rewiring"









    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "FranklyBrad.com Website"
        meta = "Containerized website"
        tagline = "This website was built with Hugo and packaged as a container based on the Alpine Linux image. It's running behind a Traefik 2 container for reverse-proxy and Let's Encrypt certs."
        url = "//github.com/bradleyfrank/hugo-site"

        [[params.projects.list]]
        title = "NAS Replacement With ZFS"
        meta = "Home storage and file server"
        tagline = "For cost consideration, I wanted to migrate an old NAS to use the existing HDD storage in my home server. I settled on ZFS with mirrored vdevs for redundancy. I added local snapshots, scheduled SMART scans, and offsite backup to add robustness, and Samba sharing for easy file access."

        [[params.projects.list]]
        title = "Nextcloud Implementation"
        meta = "File sharing and collaboration"
        tagline = "A more secure and privacy friendly option for sharing documents with my family, I control the fullstack. My instance runs in Docker and uses a MariaDB and Redis backend."

        [[params.projects.list]]
        title = "Backups using Borg"
        meta = "Backups with built-in encryption"
        tagline = "I repurposed the old NAS to be a simple server that can take backups from the new file server. BorgBackup dedupes application and user data before encrypting it on the remote system. From there, it's backed up again to cloud storage (B2)."

        [[params.projects.list]]
        title = "Plex Media Server"
        meta = "Streaming media service"
        tagline = "There's still a lot of movies/tv/music you can't rely on to be commercially streaming, so I converted my physical media to digital using various tools. Also great for watching all of the wedding media and home videos."







    [params.information]
        enable = true

        [[params.information.list]]
        title = "Trainings & Classes"
        [[params.information.list.items]]
        details = "Red Hat: RHEL 8, Advanced Container CI/CD Pipeline Orchestration, Ansible Automation Technical Workshop"
        [[params.information.list.items]]
        details = "DevOps Foundations: Continuous Delivery/Continuous Integration"
        [[params.information.list.items]]
        details = "Global Knowledge: AWS Technical Essentials"
        [[params.information.list.items]]
        details = "Opsview: Essentials, Administration, Advanced Administration"

        [[params.information.list.items]]
        details = "Puppet Labs: Fundamentals, Practitioner"
        [[params.information.list.items]]
        details = "Harvard IT Academy: Agile Foundations"
        [[params.information.list.items]]
        details = "MITx: Introduction to Computer Science and Programming Using Python (6.00.1x)"
        [[params.information.list.items]]
        details = "Harvard Extension School: Fundamentals of Website Design (CSCI-E12), Introduction to Content Management Systems (CSCI-E30), Building Dynamic Websites (CSCI-E75)"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fa fa-id-card"
        url = "https://www.youracclaim.com/badges/e8be4699-1d77-4e9e-b2ce-436a2b3d69c4"
        title = "acclaim verification"





