version: '3'

services:
  franklybrad:
    container_name: franklybrad
    image: franklybrad:latest
    hostname: franklybrad
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.franklybrad.entrypoints=http"
      - "traefik.http.routers.franklybrad.rule=Host(`franklybrad.com`)"
      - "traefik.http.middlewares.franklybrad-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.franklybrad.middlewares=franklybrad-https-redirect"
      - "traefik.http.routers.franklybrad-secure.entrypoints=https"
      - "traefik.http.routers.franklybrad-secure.rule=Host(`franklybrad.com`)"
      - "traefik.http.routers.franklybrad-secure.tls=true"
      - "traefik.http.routers.franklybrad-secure.tls.certresolver=http"
      - "traefik.http.routers.franklybrad-secure.service=franklybrad"
      - "traefik.http.services.franklybrad.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      # - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www.franklybrad.com/(.*)"
      # - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://franklybrad.com/$${1}"
      # - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
      # - "traefik.http.routers.franklybrad.middlewares=www-redirect"
    networks:
      - proxy
    ports:
      - "8030:80"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  proxy:
    external: true
